# --- Site Settings ---
title: "Qiming Ye 叶启明"
description: "AI-driven adaptive planning for urban transport–energy systems: SEVs, E-buses, and car-lite transitions."
url: "https://ye-qiming.github.io"
baseurl: ""   # user site must be empty
repository: "ye-qiming/ye-qiming.github.io"
google_scholar_stats_use_cdn: false

# Analytics (use one of them as needed)
google_analytics_id:    # theme-specific key (keep if theme expects it)
google_analytics:       # jekyll-seo-tag key (fill with GA4 ID like G-XXXXXXX)

# SEO verifications (optional)
google_site_verification:
bing_site_verification:
baidu_site_verification:

# --- Author ---
author:
  name: "Qiming Ye (叶启明)"
  avatar: "images/qmy_PROFILE.png"
  bio: "ETH Zurich"
  location: "Singapore ETH Centre, Singapore"
  employer:
  pubmed:
  googlescholar: "https://scholar.google.com/citations?user=7haYvj8AAAAJ"
  email: "qiming.ye@sec.ethz.ch"
  researchgate: "https://www.researchgate.net/profile/Qiming-Ye-2?ev=hdr_xprf"
  github: "ye-qiming"
  linkedin: "https://www.linkedin.com/in/qimingye/"
  orcid: "https://orcid.org/0000-0003-4732-2042"
  twitter:
  youtube:

# --- Reading Files ---
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --- Conversion ---
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# --- Markdown Processing ---
kramdown:
  input: GFM
  math_engine: katex
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- Defaults ---
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# --- Sass/SCSS ---
sass:
  sass_dir: _sass
  style: compressed

# --- Outputting ---
permalink: /:categories/:title/
timezone: Asia/Singapore

# --- Plugins ---
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji

# If you run locally with --safe, keep whitelist; otherwise can remove.
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji

# --- HTML Compression ---
compress_html:
  clippings: all
  ignore:
    envs: development
